CREATE TABLE games
(
    ID              INT          NOT NULL AUTO_INCREMENT,
    SEASON          INT          NOT NULL,
    WEEK            INT          NOT NULL,
    HOME_TEAM_NAME  VARCHAR(100) NOT NULL,
    HOME_TEAM_SCORE INT          NULL,
    AWAY_TEAM_NAME  VARCHAR(100) NOT NULL,
    AWAY_TEAM_SCORE INT          NULL,
    PRIMARY KEY (`id`),
    UNIQUE (SEASON, WEEK)
);

CREATE TABLE guesses
(
    ID              INT NOT NULL AUTO_INCREMENT,
    PLAYER_ID       INT NOT NULL,
    HOME_TEAM_SCORE INT NULL,
    AWAY_TEAM_SCORE INT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE users
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    SCORE      INT          NOT NULL,
    PRIMARY KEY (`id`)
);


CREATE TABLE weeklies
(
    ID          INT NOT NULL AUTO_INCREMENT,
    WEEK_NUMBER INT NOT NULL,
    PLAYER_ID   INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT
        FOREIGN KEY FK_WEEK_PLAYER (PLAYER_ID)
            REFERENCES users (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE periods
(
    ID            INT NOT NULL AUTO_INCREMENT,
    PERIOD_NUMBER INT NOT NULL,
    PLAYER_ID     INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT
        FOREIGN KEY FK_PERIOD_PLAYER (PLAYER_ID)
            REFERENCES users (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE games_guesses
(
    GAMES_ID INT NOT NULL,
    GUESS_ID INT NOT NULL,
    PRIMARY KEY (GAMES_ID, GUESS_ID),
    CONSTRAINT
        FOREIGN KEY FK_GAMES_GAMES_GUESSES (GAMES_ID)
            REFERENCES games (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT
        FOREIGN KEY FK_GUESS_GAMES_GUESSES (GUESS_ID)
            REFERENCES games (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE players_guesses
(
    PLAYER_ID INT NOT NULL,
    GUESS_ID  INT NOT NULL,
    PRIMARY KEY (`PLAYER_ID`, `GUESS_ID`),
    CONSTRAINT
        FOREIGN KEY FK_PLAYERS_PLAYER_GUESSES (PLAYER_ID)
            REFERENCES users (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT
        FOREIGN KEY FK_GUESS_PLAYER_GUESSES (GUESS_ID)
            REFERENCES guesses (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE

);

